### ISSUE TITLE
When importing it will be good to indicate the order: Nodes and then Edges

### ISSUE THREAD

**Issue by TEDI-London** [vivianlikeyeah/module_mate#13]
When clicking import Edges, and choosing a previously saved Edges file, nothing apperas on screen. It will be useful to:
- display a message as of why nothing gets displayed (i.e. Please import the Nodes file first)
- indicate on the left hand navigation that Import nodes needs to be done first. Maybe Import Nodes (1), Import Edges (2)

**Comment by vivianlikeyeah** [comment]
Thanks for the suggestion. I've done the following: 

Added a tooltip on the upload button that explains this will apply to all nodes that are currently visible. 
Numbered the import buttons
Displayed an alert when a user uploads edges when there are not any nodes present in the network. 


1864998

Let me know how that goes!
