### ISSUE TITLE
Triple click bug (or feature)

### ISSUE THREAD

**Issue by TEDI-London** [vivianlikeyeah/module_mate#15]
When trying to add an edge to imported nodes and triple clicking on a node, the node border appears moved a bit to the top-right:

![image](https://user-images.githubusercontent.com/66628394/107975977-cb429e00-6fb0-11eb-9833-d94da1b862d6.png)

**Comment by vivianlikeyeah** [comment]
Hello :) This is actually the node connecting to itself! 
Would you like me to look into disabling this? Not sure entirely how I would do this yet.
